# Generated by Django 2.0 on 2018-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(auto_now=True)),
                ('body', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
